name: Run Tests on Push
on:
  push:
    branches-ignore:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Set up uv
        uses: astral-sh/setup-uv@v4
      - name: Sync dependencies
        run: uv sync --all-groups
      - name: Run Tests
        run: uv run pytest tests
